version: '2'

services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
    command: /bin/true

  db:
    container_name: db
    image: mariadb:latest
    volumes_from:
      - db_data
    # The setting below enables custom configuration
    # that turns on the MySQL query log
    # volumes:
    #   - ./compose/mariadb:/etc/mysql/conf.d

    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

    ports:
      - "3306:3306"

  trust:
    image: indigoiam/trustanchors
    # build:
    #  context: ./docker/trust-anchors
    command: /bin/true

  iam-be:
    container_name: iam-be
    build:
      context: .
      dockerfile: ./iam-login-service/docker/Dockerfile

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1044 -Dspring.profiles.active=mysql-test
      IAM_JAR: /code/iam-login-service/target/iam-login-service.war
      IAM_HOST: iam.local.io
      IAM_BASE_URL: https://iam.local.io
      IAM_ISSUER: https://iam.local.io
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"

      # IAM_TOMCAT_ACCESS_LOG_ENABLED: "true"

      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd

      IAM_GOOGLE_CLIENT_ID: ${IAM_GOOGLE_CLIENT_ID}
      IAM_GOOGLE_CLIENT_SECRET: ${IAM_GOOGLE_CLIENT_SECRET}

      IAM_IAM_TEST_CLIENT_ID: ${IAM_IAM_TEST_CLIENT_ID}
      IAM_IAM_TEST_CLIENT_SECRET: ${IAM_IAM_TEST_CLIENT_SECRET}

      # IAM_SAML_IDP_METADATA: file:///code/compose/metadata/test-idp.cloud.cnaf.infn.it.metadata.xml 
      # IAM_SAML_ENTITY_ID: urn:iam:iam-devel
      # IAM_SAML_ENTITY_ID: https://iam.local.io

    ports:
      - "1044:1044"

    volumes_from:
      - trust

    volumes:
      - .:/code:ro
      - /dev/urandom:/dev/random
      - ./compose/multiple-oidc-providers/application.yml:/indigo-iam/config/application.yml

  client:
    build:
      context: .
      dockerfile: ./iam-test-client/docker/Dockerfile

    container_name: client

    environment:
      TZ: Europe/Rome
      IAM_CLIENT_PORT: 8080
      IAM_CLIENT_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1045
      IAM_CLIENT_ID: client
      IAM_CLIENT_SECRET: secret
      IAM_CLIENT_ISSUER: https://iam.local.io/
      IAM_CLIENT_REDIRECT_URIS: https://iam.local.io/iam-test-client/openid_connect_login
      IAM_CLIENT_USE_FORWARD_HEADERS: "true"
      #IAM_CLIENT_EXT_AUTHN_HINT: saml:exampleIdp
      IAM_CLIENT_JAR: /code/iam-test-client/target/iam-test-client.jar

    ports:
      - "1045:1045"

    volumes_from:
      - trust

    volumes:
      - .:/code:ro

  iam:
    build:
      context: ./docker/nginx/

    depends_on:
      - iam-be
      - client

    dns_search: local.io

    container_name: iam

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"

    volumes:
      - /dev/urandom:/dev/random

    networks:
      default:
        aliases:
          - iam.local.io

# browser:
#   image: jess/firefox
#   container_name: browser
#
#   environment:
#     DISPLAY: 172.17.8.1:0
