#
# Copyright (c) Istituto Nazionale di Fisica Nucleare (INFN). 2016-2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

server:
  servlet:
    session:
      timeout: ${IAM_SESSION_TIMEOUT_SECS:1800}
        
  error:
    path: /error
    
  port: ${IAM_PORT:8080}
  
  tomcat:
    accesslog:
      enabled: ${IAM_TOMCAT_ACCESS_LOG_ENABLED:false}
      directory: ${IAM_TOMCAT_ACCESS_LOG_DIRECTORY:/tmp}
      pattern: "%{X-Forwarded-For}i %l %u %t \"%r\" %s %b"

  forward-headers-strategy: ${IAM_FORWARD_HEADERS_STRATEGY:none}
  
spring:
  redis:
    
    host: ${IAM_SPRING_REDIS_HOST:localhost}
    port: ${IAM_SPRING_REDIS_PORT:6379}
    password: ${IAM_SPRING_REDIS_PASSWORD:}
    
  application:
    name: INDIGO IAM
  
  session:
    timeout: ${IAM_SESSION_TIMEOUT_SECS:1800}
    store-type: ${IAM_SPRING_SESSION_STORE_TYPE:none}
    redis:
      flush-mode: on-save
      namespace: iam:session
     
  security:
    filter:
      order: 1
       
  profiles:
    default: h2-test
    group:
     "h2-test": "h2,saml,registration"
     "h2-test-redis": "h2,saml,registration,redis-test"
     "mysql-test": "mysql,saml,registration"
     "mysql-test-tc": "mysql-test-tc,saml,registration"
     "mysql-test-tc-redis": "mysql-test-tc,saml,registration,redis-test"
     "prod": "mysql,flyway-repair"
    
  jpa:
    generate-ddl: true
    open-in-view: false

  mail:
    host: ${IAM_MAIL_HOST:localhost}
    port: ${IAM_MAIL_PORT:25}
    username: ${IAM_MAIL_USERNAME:}
    password: ${IAM_MAIL_PASSWORD:}

  flyway:
    table: schema_version
    
  freemarker:
    template-loader-path: ${IAM_CUSTOM_TEMPLATE_LOCATION:classpath:/email-templates}

iam:
  
  host: ${IAM_HOST:localhost}
  baseUrl: ${IAM_BASE_URL:http://${iam.host}:8080}
  issuer: ${IAM_ISSUER:http://${iam.host}:8080}
  topbarTitle: ${IAM_TOPBAR_TITLE:INDIGO IAM for ${iam.organisation.name}}
  
  jwk:
    keystore-location: ${IAM_KEY_STORE_LOCATION:classpath:keystore.jwks}
    default-key-id: ${IAM_JWK_DEFAULT_KEY_ID:rsa1}
    default-jwe-decrypt-key-id: ${IAM_JWK_DEFAULT_JWE_DECRYPT_KEY_ID:${iam.jwk.default-key-id}}
    default-jwe-encrypt-key-id: ${IAM_JWK_DEFAULT_JWE_ENCRYPT_KEY_ID:${iam.jwk.default-key-id}}
    default-jws-algorithm: ${IAM_JWK_DEFAULT_JWS_ALGORITHM:RS256}
    default-jwe-algorithm: ${IAM_JWT_DEFAULT_JWE_ALGORITHM:RSA_OAEP_256} 
    
  jwt-profile:
    default-profile: ${IAM_JWT_DEFAULT_PROFILE:iam}
  
  logo:
    url: ${IAM_LOGO_URL:resources/images/indigo-logo.png}
    dimension: ${IAM_LOGO_DIMENSION:200}
    height: ${IAM_LOGO_HEIGHT:150}
    width: ${IAM_LOGO_WIDTH:200}
  
  token:
    # This is the registration access token lifetime
    lifetime: ${IAM_REGISTRATION_TOKEN_LIFETIME:-1}  

  organisation:
    name: ${IAM_ORGANISATION_NAME:indigo-dc}
  
  privacyPolicy:
    url: ${IAM_PRIVACY_POLICY_URL:}
    text: ${IAM_PRIVACY_POLICY_TEXT:Privacy policy}
  
  loginButton:
    text: ${IAM_LOGIN_BUTTON_TEXT:Sign in}

  enableScopeAuthz: ${IAM_ENABLE_SCOPE_AUTHZ:true}

  access_token:
    include_authn_info: ${IAM_ACCESS_TOKEN_INCLUDE_AUTHN_INFO:false}
    include_scope: ${IAM_ACCESS_TOKEN_INCLUDE_SCOPE:false}
    include_nbf: ${IAM_ACCESS_TOKEN_INCLUDE_NBF:false}

  actuator-user:
    username: ${IAM_ACTUATOR_USER_USERNAME:actuator-user}
    password: ${IAM_ACTUATOR_USER_PASSWORD:actuator-password}
  
  local-resources:
    enable: ${IAM_LOCAL_RESOURCES_ENABLE:false}
    location: ${IAM_LOCAL_RESOURCES_LOCATION:file:/indigo-iam/local-resources}
  
  device-code:
    allow-complete-verification-uri: ${IAM_DEVICE_CODE_ALLOW_COMPLETE_VERIFICATION_URI:true}
  
  registration:
    show-registration-button-in-login-page: ${IAM_REGISTRATION_SHOW_REGISTRATION_BUTTON_IN_LOGIN_PAGE:true}
    require-external-authentication: ${IAM_REGISTRATION_REQUIRE_EXTERNAL_AUTHENTICATION:false}
    authentication-type: ${IAM_REGISTRATION_AUTHENTICATION_TYPE:oidc}
    oidc-issuer: ${IAM_REGISTRATION_OIDC_ISSUER:https://example.org}
    saml-entity-id: ${IAM_REGISTRATION_SAML_ENTITY_ID:urn:example}
    
  local-authn:
    login-page-visibility: ${IAM_LOCAL_AUTHN_LOGIN_PAGE_VISIBILITY:visible}
    enabled-for: ${IAM_LOCAL_AUTHN_ENABLED_FOR:all}
  
  customization:
    custom-login-page-content-url: ${IAM_CUSTOMIZATION_CUSTOM_LOGIN_PAGE_CONTENT_URL}
    include-custom-login-page-content: ${IAM_CUSTOMIZATION_INCLUDE_CUSTOM_LOGIN_PAGE_CONTENT:false}
  
  user-profile:
    editable-fields:
    - email
    - name
    - picture
    - surname
   
  aarc-profile:
    urn-namespace: ${IAM_AARC_PROFILE_URN_NAMESPACE:example:iam}
    
  external-connectivity-probe:
    enabled: ${IAM_HEALTH_EXTERNAL_CONNECTIVITY_PROBE_ENABLED:false}
    endpoint: ${IAM_HEALTH_EXTERNAL_CONNECTIVITY_PROBE_ENDPOINT:https://www.google.it}
    timeout-in-secs: ${IAM_HEALTH_EXTERNAL_CONNECTIVITY_PROBE_TIMEOUT_IN_SECS:10}
    
  account-linking:
    enable: ${IAM_ACCOUNT_LINKING_ENABLE:true}

x509:
  trustAnchorsDir: ${IAM_X509_TRUST_ANCHORS_DIR:/etc/grid-security/certificates}
  trustAnchorsRefreshMsec: ${IAM_X509_TRUST_ANCHORS_REFRESH:14400}
  tlsVersion: ${IAM_X509_TLS_VERSION:TLSv1}
    
notification:
  disable: ${IAM_NOTIFICATION_DISABLE:false}
  mailFrom: ${IAM_NOTIFICATION_FROM:indigo@localhost}
  taskDelay: ${IAM_NOTIFICATION_TASK_DELAY:5000}
  cleanupAge: ${IAM_NOTIFICATION_CLEANUP_AGE:30}
  adminAddress: ${IAM_NOTIFICATION_ADMIN_ADDRESS:indigo-alerts@localhost}
  admin-notification-policy: ${IAM_NOTIFICATION_ADMIN_NOTIFICATION_POLICY:notify-address}
  group-manager-notification-policy: ${IAM_NOTIFICATION_GROUP_MANAGER_NOTIFICATION_POLICY:notify-gms-and-admins}
  subject:
    confirmation: Confirm your ${iam.organisation.name} registration request
    activated: Your ${iam.organisation.name} account is now active
    rejected: Your request for a ${iam.organisation.name} account has been rejected
    adminHandleRequest: New ${iam.organisation.name} account request
    resetPassword: Reset your ${iam.organisation.name} account password

task:
  tokenCleanupPeriodMsec: ${IAM_TOKEN_CLEANUP_PERIOD_MSEC:300000}
  approvalCleanupPeriodMsec: ${IAM_APPROVAL_CLEANUP_PERIOD_MSEC:300000}
  deviceCodeCleanupPeriodMsec: ${IAM_DEVICE_CODE_CLEANUP_PERIOD_MSEC:300000}

client-registration:
  allow-for: ${IAM_CLIENT_REGISTRATION_ALLOW_FOR:ANYONE}
  enable: ${IAM_CLIENT_REGISTRATION_ENABLE:true}

management:
  health:
      redis:
        enabled: ${IAM_HEALTH_REDIS_PROBE_ENABLED:false} 
      mail:
        enabled: ${IAM_HEALTH_MAIL_PROBE_ENABLED:false} 
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
        - info
        - health
  endpoint:
    info:
      enabled: true
    health: 
      show-components: always 
      enabled: true
      show-details: when-authorized
      roles:
      - ACTUATOR
      
    metrics:
      enabled: true
    
rcauth:
  enabled: ${IAM_RCAUTH_ENABLED:false}
  label: ${IAM_RCAUTH_LABEL:RCAuth.eu online CA}
  issuer: ${IAM_RCAUTH_ISSUER}
  client-id: ${IAM_RCAUTH_CLIENT_ID}
  client-secret: ${IAM_RCAUTH_CLIENT_SECRET}
  idp-hint: ${IAM_RCAUTH_IDP_HINT}
  key-size: ${IAM_RCAUTH_KEY_SIZE:2048}
  cert-lifetime-seconds: ${IAM_RCAUTH_CERT_LIFETIME_SECONDS:259200}

proxycert:
  enabled: ${IAM_PROXYCERT_ENABLED:true}
  key-size: ${IAM_PROXYCERT_KEY_SIZE:2048}
  max-lifetime-seconds: ${IAM_PROXYCERT_MAX_LIFETIME_SECONDS:43200}
