spring:
  datasource:
    dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
    url: jdbc:mysql://${IAM_DB_HOST:dev.local.io}:${IAM_DB_PORT:3306}/${IAM_DB_NAME:iam}
    username: ${IAM_DB_USERNAME:iam}
    password: ${IAM_DB_PASSWORD:pwd}
    max-active: ${IAM_DB_MAX_ACTIVE:100}
    max-idle:  ${IAM_DB_MAX_IDLE:5}
    initial-size: ${IAM_DB_INITIAL_SIZE:1}
    test-while-idle: ${IAM_DB_TEST_WHILE_IDLE:true}
    test-on-borrow: ${IAM_DB_TEST_ON_BORROW:true}
    validation-query: ${IAM_DB_VALIDATION_QUERY:SELECT 1}
    time-between-eviction-runs-millis: ${IAM_DB_TIME_BETWEEN_EVICTION_RUNS_MILLIS:5000}
    min-evictable-idle-time-millis: ${IAM_DB_MIN_EVICTABLE_IDLE_TIME_MILLIS:60000}

  jpa:
    openInView: false