version: '2.1'

services:
  db_data:
    image: busybox
    volumes:
      - /var/lib/mysql
    command: /bin/true

  db:
    container_name: db
    image: mariadb:latest
    volumes_from:
      - db_data
    # The setting below enables custom configuration
    # that turns on the MySQL query log
    # volumes:
    #   - ./compose/mariadb:/etc/mysql/conf.d

    environment:
      TZ: Europe/Rome
      MYSQL_ROOT_PASSWORD: pwd
      MYSQL_USER: iam
      MYSQL_PASSWORD: pwd
      MYSQL_DATABASE: iam

  trust:
    image: indigoiam/trustanchors:latest

  iam-be:
    container_name: iam-be
    image: ${IAM_IMAGE:-indigoiam/iam-login-service:latest}

    environment:
      TZ: Europe/Rome
      IAM_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Dspring.profiles.active=mysql-test -DmockX509Authentication
      IAM_HOST: ${IAM_HOSTNAME:-iam.local.io}
      IAM_BASE_URL: https://${IAM_HOSTNAME:-iam.local.io}
      IAM_ISSUER: https://${IAM_HOSTNAME:-iam.local.io}
      IAM_USE_FORWARDED_HEADERS: "true"
      IAM_NOTIFICATION_DISABLE: "true"
      # IAM_TOMCAT_ACCESS_LOG_ENABLED: "true"

      IAM_DB_HOST: db
      IAM_DB_USERNAME: iam
      IAM_DB_PASSWORD: pwd

      IAM_GOOGLE_CLIENT_ID: ${IAM_GOOGLE_CLIENT_ID}
      IAM_GOOGLE_CLIENT_SECRET: ${IAM_GOOGLE_CLIENT_SECRET}

      # IAM_SAML_IDP_METADATA: file:///code/compose/metadata/test-idp.cloud.cnaf.infn.it.metadata.xml 
      # IAM_SAML_ENTITY_ID: urn:iam:iam-devel
      # IAM_SAML_ENTITY_ID: https://iam.local.io

    ports:
      - "1044:1044"

    volumes_from:
      - trust

    volumes:
      - /dev/urandom:/dev/random

  client:
    image: ${IAM_CLIENT_IMAGE:-indigoiam/iam-test-client:latest}
    container_name: client

    environment:
      TZ: Europe/Rome
      IAM_CLIENT_PORT: 8080
      IAM_CLIENT_JAVA_OPTS: -Djava.security.egd=file:/dev/./urandom -Xdebug -Xrunjdwp:server=y,transport=dt_socket,suspend=n,address=1045
      IAM_CLIENT_ID: client
      IAM_CLIENT_SECRET: secret
      IAM_CLIENT_ISSUER: https://${IAM_HOSTNAME:-iam.local.io}/
      IAM_CLIENT_REDIRECT_URIS: https://${IAM_HOSTNAME:-iam.local.io}/iam-test-client/openid_connect_login
      IAM_CLIENT_USE_FORWARD_HEADERS: "true"
    ports:
      - "1045:1045"

    volumes_from:
      - trust

  iam:
    container_name: iam
    image: indigoiam/nginx:latest
    depends_on:
      - iam-be
      - client

    dns_search: local.io

    environment:
      TZ: Europe/Rome
      NGINX_HOST: iam
      NGINX_PORT: 443

    ports:
      - "443:443"

    volumes:
      - /dev/urandom:/dev/random

    networks:
      default:
        aliases:
          - iam.local.io

  selenium-hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
    environment:
      - GRID_TIME0UT=0

  selenium-chrome:
    image: selenium/node-chrome:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  selenium-firefox:
    image: selenium/node-firefox:3.8.1
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444

  iam-robot-testsuite:
    image: ${IAM_TESTSUITE_IMAGE:-indigoiam/iam-robot-testsuite:latest}
    environment:
      IAM_TESTSUITE_DEBUG: ${IAM_TESTSUITE_DEBUG}
      SERVICE_WAIT_TIMEOUT: ${IAM_TESTSUITE_SERVICE_WAIT_TIMEOUT:-120}
      TESTSUITE_REPO: ${IAM_TESTSUITE_REPO:-https://github.com/indigo-iam/iam-robot-testsuite.git}
      TESTSUITE_BRANCH: ${IAM_TESTSUITE_BRANCH:-develop}
      IAM_BASE_URL: https://${IAM_HOSTNAME:-iam.local.io}
      IAM_TEST_CLIENT_URL: https://${IAM_HOSTNAME:-iam.local.io}/iam-test-client
      REMOTE_URL: http://selenium-hub:4444/wd/hub 
      BROWSER: ${IAM_TESTSUITE_BROWSER:-chrome}
      TIMEOUT: ${IAM_TESTSUITE_TIMEOUT:-5}
      IMPLICIT_WAIT: ${IAM_TESTSUITE_IMPLICIT_WAIT:-2}
      SPEED: ${IAM_TESTSUITE_SPEED:-0}
      TESTSUITE_OPTS: ${IAM_TESTSUITE_OPTS}
      ADMIN_USER: ${IAM_TESTSUITE_ADMIN_USER:-admin}
      ADMIN_PASSWORD: ${IAM_TESTSUITE_ADMIN_PASSWORD:-password}
      CLIENT_ID: ${IAM_TESTSUITE_CLIENT_ID:-client-cred}
      CLIENT_SECRET: ${IAM_TESTSUITE_CLIENT_SECRET:-secret}
      TOKEN_EXCHANGE_CLIENT_ID: ${IAM_TESTSUITE_TOKEN_EXCHANGE_CLIENT_ID:-token-exchange-actor}
      TOKEN_EXCHANGE_CLIENT_SECRET: ${IAM_TESTSUITE_TOKEN_EXCHANGE_CLIENT_SECRET:-secret}

    depends_on:
      - iam
      - selenium-hub
      - selenium-chrome
      - selenium-firefox
